import 'package:intl/intl.dart';
import 'package:on_stage_app/app/features/artist/domain/models/artist_model.dart';
import 'package:on_stage_app/app/features/event/domain/models/event_model.dart';
import 'package:on_stage_app/app/features/notifications/domain/models/stage_notification_model.dart';
import 'package:on_stage_app/app/features/song/domain/models/song_model.dart';

class SongDummy {
  static const thisWeekEventsDummy = <EventModel>[
    EventModel(
      id: 1,
      name: 'Vineri seara',
      date: '2023-10-01',
      rehearsalsDate: ['2023-12-01'],
      staggersId: ['stagger_id_1'],
      adminsId: ['admin_id_1'],
      eventItemIds: ['event_item_id_1'],
      location: 'Location 1',
      imageUrl: 'https://via.placeholder.com/150',
    ),
    EventModel(
      id: 2,
      name: 'Tineret Speranta',
      date: '2023-11-26',
      rehearsalsDate: ['2023-12-02'],
      staggersId: ['stagger_id_2'],
      adminsId: ['admin_id_2'],
      eventItemIds: ['event_item_id_2'],
      location: 'Location 2',
      imageUrl: 'https://via.placeholder.com/150',
    ),
    EventModel(
      id: 3,
      name: 'Tineret Betania',
      date: '2023-11-27',
      rehearsalsDate: ['2023-12-03'],
      staggersId: ['stagger_id_3'],
      adminsId: ['admin_id_3'],
      eventItemIds: ['event_item_id_3'],
      location: 'Location 3',
      imageUrl: 'https://via.placeholder.com/150',
    ),
    EventModel(
      id: 4,
      name: 'Peniel',
      date: '2023-11-24',
      rehearsalsDate: ['2023-12-04'],
      staggersId: ['stagger_id_4'],
      adminsId: ['admin_id_4'],
      eventItemIds: ['event_item_id_4'],
      location: 'Location 4',
      imageUrl: 'https://via.placeholder.com/150',
    ),
    ];
  static const upcomingEventsDummy = <EventModel>[
    EventModel(
      id: 5,
      name: 'Ekklesia Arad',
      date: '2023-12-05',
      rehearsalsDate: ['2023-12-05'],
      staggersId: ['stagger_id_5'],
      adminsId: ['admin_id_5'],
      eventItemIds: ['event_item_id_5'],
      location: 'Location 5',
      imageUrl: 'https://via.placeholder.com/150',
    ),
    EventModel(
      id: 6,
      name: 'Conferinta',
      date: '2023-12-06',
      rehearsalsDate: ['2023-12-06'],
      staggersId: ['stagger_id_6'],
      adminsId: ['admin_id_6'],
      eventItemIds: ['event_item_id_6'],
      location: 'Location 6',
      imageUrl: 'https://via.placeholder.com/150',
    ),
    ];
  static const pastEventsDummy = <EventModel>[
    EventModel(
      id: 7,
      name: 'Ez az a nap',
      date: '2023-12-07',
      rehearsalsDate: ['2023-12-07'],
      staggersId: ['stagger_id_7'],
      adminsId: ['admin_id_7'],
      eventItemIds: ['event_item_id_7'],
      location: 'Location 7',
      imageUrl: 'https://via.placeholder.com/150',
    ),
    EventModel(
      id: 8,
      name: 'Seara de colinde',
      date: '2023-12-08',
      rehearsalsDate: ['2023-12-08'],
      staggersId: ['stagger_id_8'],
      adminsId: ['admin_id_8'],
      eventItemIds: ['event_item_id_8'],
      location: 'Location 8',
      imageUrl: 'https://via.placeholder.com/150',
    ),
    ];

  static const notificationsDummy = <StageNotification>[
    //fill with dummy data
    StageNotification(
      id: 1,
      title: 'Ready to go live?',
      body: 'Julia invited you to join the stage on Friday Night, 8:00 PM',
      createdAt: 'today',
    ),
    StageNotification(
      id: 1,
      title: 'Friend Request',
      body: 'David sent you a friend request',
      createdAt: 'today',
    ),
    StageNotification(
      id: 1,
      title: 'Ready to go live?',
      body: 'Julia invited you to join the stage on Friday Night, 8:00 PM',
      createdAt: 'today',
    ),
    StageNotification(
      id: 1,
      title: 'Ready to go live?',
      body: 'Julia invited you to join the stage on Friday Night, 8:00 PM',
      createdAt: 'today',
    ),
    StageNotification(
      id: 1,
      title: 'Friend Request',
      body: 'David sent you a friend request',
      createdAt: 'today',
    ),
    StageNotification(
      id: 1,
      title: 'Ready to go live?',
      body: 'Julia invited you to join the stage on Friday Night, 8:00 PM',
      createdAt: 'today',
    ),
  ];
  static const List<SongModel> songs = [
    SongModel(
      id: 1,
      title: 'Nu e munte prea mare',
      lyrics: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      tab: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      key: 'C# major',
      createdAt: '2021-08-01T00:00:00.000Z',
      updatedAt: '2021-08-01T00:00:00.000Z',
      artist: Artist(
        id: 1,
        fullName: 'BBSO',
        songIds: [1, 2],
        imageUrl: 'assets/images/band1.png',
      ),
      album: 'Tabara 477',
      capo: 1,
    ),
    //add more of these
    SongModel(
      id: 2,
      title: 'Ala bala portocala',
      lyrics: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      tab: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      key: 'C# major',
      createdAt: '2021-08-01T00:00:00.000Z',
      updatedAt: '2021-08-01T00:00:00.000Z',
      artist: Artist(id: 1, fullName: 'Tabara 477', songIds: [1, 2]),
      album: 'Tabara 477',
      capo: 1,
    ),
    SongModel(
      id: 3,
      title: 'Isus e Rege',
      lyrics: 'Ana are mere si pere',
      tab: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      key: 'C# major',
      createdAt: '2021-08-01T00:00:00.000Z',
      updatedAt: '2021-08-01T00:00:00.000Z',
      artist: Artist(
        id: 1,
        fullName: 'Alin si Emima',
        songIds: [1, 2],
        imageUrl: 'assets/images/band3.png',
      ),
      capo: 1,
    ),
    SongModel(
      id: 4,
      title: 'Soarele neprihanirii',
      lyrics: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      tab: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      key: 'C# major',
      createdAt: '2021-08-01T00:00:00.000Z',
      updatedAt: '2021-08-01T00:00:00.000Z',
      artist: Artist(id: 1, fullName: 'El Shaddai', songIds: [1, 2]),
      album: 'Tabara 477',
      capo: 1,
    ),
    SongModel(
      id: 5,
      title: 'Astazi e craciun',
      lyrics: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      tab: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      key: 'C# major',
      createdAt: '2021-08-01T00:00:00.000Z',
      updatedAt: '2021-08-01T00:00:00.000Z',
      artist: Artist(
        id: 1,
        fullName: 'Boboc',
        songIds: [1, 2],
        imageUrl: 'assets/images/band1.png',
      ),
      album: 'Tabara 477',
      capo: 1,
    ),
    SongModel(
      id: 6,
      title: 'Yahweh se manifesta',
      lyrics: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      tab: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      key: 'C# major',
      createdAt: '2021-08-01T00:00:00.000Z',
      updatedAt: '2021-08-01T00:00:00.000Z',
      artist: Artist(id: 1, fullName: 'Test 123', songIds: [1, 2]),
      album: 'Tabara 477',
      capo: 1,
    ),
    SongModel(
      id: 7,
      title: 'Soarele neprihanirii',
      lyrics: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      tab: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      key: 'C# major',
      createdAt: '2021-08-01T00:00:00.000Z',
      updatedAt: '2021-08-01T00:00:00.000Z',
      artist: Artist(
        id: 1,
        fullName: 'Harvest Arad',
        songIds: [1, 2],
        imageUrl: 'assets/images/band2.png',
      ),
      album: 'Tabara 477',
      capo: 1,
    ),
    SongModel(
      id: 8,
      title: 'Eu sunt mic, dar Isus',
      lyrics: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      tab: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      key: 'C# major',
      createdAt: '2021-08-01T00:00:00.000Z',
      updatedAt: '2021-08-01T00:00:00.000Z',
      artist: Artist(id: 1, fullName: 'Tabara 477', songIds: [1, 2]),
      album: 'Tabara 477',
      capo: 1,
    ),
  ];
}
