name: on_stage_app
description: On Stage App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.1.12
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  go_router: ^9.0.2
  google_fonts: ^5.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.1

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/


