name: on_stage_app
description: On Stage App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  go_router: ^9.0.0
  google_fonts: ^5.1.0
  intl: ^0.18.1
  logger: ^1.4.0

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
