name: on_stage_app
description: On Stage App
version: 1.2.4+18
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"


flutter_native_splash:
  color: "#DDECF1" # Set the background color of your splash screen
  icon_background_color: "#DDECF1" # Set the background color of your splash screen icon
  image: assets/icons/logo_without_background.png # Path to your splash image
  android: true # Enable for Android
  ios: false # Enable for iOS
  android_gravity: center # Optional: Position of the image


dependencies:
  email_validator: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^14.4.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  loading_indicator: ^3.1.1
  logger: ^2.4.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  modal_bottom_sheet: ^3.0.0
  http: ^1.2.2
  change_app_package_name: ^1.4.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.2
  flutter_reorderable_grid_view: ^5.3.2
  reorderables: ^0.6.0
  flutter_svg: ^2.0.12
  flutter_slidable: ^3.1.2
  get_it: ^8.0.2
  ansi: ^0.4.2
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.4
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  flutter_secure_storage: ^9.2.2
  shimmer: ^3.0.0
  pretty_dio_logger: ^1.4.0
  sliver_tools: ^0.2.12
  intl: any
  vector_graphics: any
  connectivity_plus: ^6.1.0
  fpdart: ^1.1.0
  toggle_switch: ^2.3.0
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.5
  mime: ^2.0.0
  http_parser: ^4.0.2
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.6
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  pool: ^1.5.1
  async: ^2.11.0
  another_flushbar: ^1.12.30
  el_tooltip: ^2.2.1
  super_tooltip: ^2.0.9
  riverpod_lint: ^2.6.2
  sentry_flutter: ^8.9.0
  onboarding_overlay: ^3.2.2
  scrollable_positioned_list: ^0.3.8
  web_socket_channel: ^3.0.1
  cupertino_calendar_picker: ^2.0.0+1
  stomp_dart_client: ^2.1.0
  firebase_analytics: ^11.3.6
  flutter_dotenv: ^5.2.1
  purchases_flutter: ^8.3.0
  purchases_ui_flutter: ^8.3.0
  socket_io_client: ^3.0.2
  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.1
  forui: ^0.8.0
  markdown: ^7.2.2
  flutter_markdown: ^0.7.4+3
  flutter_lucide: ^1.6.0
  auto_size_text: ^3.0.0
  url_launcher: ^6.3.1
  synchronized: ^3.3.0+3
  force_update_helper: ^0.1.5
  firebase_remote_config: ^5.2.0
  image_cropper: ^8.0.2
  permission_handler: ^11.3.1
  path: any
dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.2
  very_good_analysis: ^6.0.0
  flutter_gen_runner: ^5.8.0
  drift_dev: ^2.21.2


flutter_gen:
  output: lib/resources/generated
  line_length: 160
  integrations:
    flutter_svg: true

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icons/logo-onstage.png"
  adaptive_icon_background: "#DDECF1"
  adaptive_icon_foreground: "assets/icons/logo_without_background.png"


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/profile1.png
    - assets/images/profile2.png
    - .env
