name: on_stage_app
description: On Stage App
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"


flutter_native_splash:
  image: assets/images/ic_launcher.png
  color: "DCECF1"


dependencies:
  email_validator: ^3.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.1
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  loading_indicator: ^3.1.1
  logger: ^2.4.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  modal_bottom_sheet: ^3.0.0
  http: ^1.2.2
  change_app_package_name: ^1.3.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.1+2
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_reorderable_grid_view: ^5.0.1
  reorderables: ^0.6.0
  flutter_svg: ^2.0.10+1
  flutter_slidable: ^3.1.1
  get_it: ^7.7.0
  ansi: ^0.4.2
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  retrofit_generator: ^9.1.2
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.2.2
  shimmer: ^3.0.0
  pretty_dio_logger: ^1.4.0
  sliver_tools: ^0.2.12


  intl: any
  vector_graphics: any
  connectivity_plus: ^6.0.5
  fpdart: ^1.1.0
  toggle_switch: ^2.3.0
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.4
  mime: ^1.0.6
  http_parser: ^4.0.2
  sign_in_with_apple: ^6.1.2
  crypto: ^3.0.5
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  drift: ^2.20.2
  drift_flutter: ^0.2.0
  pool: ^1.5.1
  async: ^2.11.0
  another_flushbar: ^1.12.30
  el_tooltip: ^2.2.1
  super_tooltip: ^2.0.8
  riverpod_lint: ^2.3.13
  sentry_flutter: ^8.9.0
  onboarding_overlay: ^3.2.2
  scrollable_positioned_list: ^0.3.8
  cupertino_calendar_picker: ^2.0.0+1
dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.4.0
  very_good_analysis: ^6.0.0
  flutter_gen_runner: ^5.6.0
  drift_dev: ^2.20.3


flutter_gen:
  output: lib/resources/generated
  line_length: 160
  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/profile1.png
    - assets/images/profile2.png