name: on_stage_app
description: On Stage App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter_native_splash:
  image: assets/images/ic_launcher.png
  color: "DCECF1"

dependencies:
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.3 # Using an earlier version that might be compatible
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  json_annotation: ^4.9.0
  loading_indicator: ^3.1.1
  logger: ^2.3.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  modal_bottom_sheet: ^3.0.0
  http: ^1.2.1
  change_app_package_name: ^1.1.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_reorderable_grid_view: ^4.0.0
  reorderables: ^0.6.0
  flutter_svg: ^2.0.10+1
  flutter_chord: ^0.1.2
  flutter_slidable: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.2
  very_good_analysis: ^5.1.0
  flutter_gen_runner: ^5.4.0


flutter_gen:
  output: lib/resources/generated
  line_length: 160
  integrations:
    flutter_svg: true

# Temporary fix for the issue with the meta package
dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/profile1.png
    - assets/images/profile2.png
    - assets/icons/
