// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPYY7_-cEcqNDo-e88XBIBPeXEHMcS8rg',
    appId: '1:895845013571:android:c29de15d7e9987ed2f9cf6',
    messagingSenderId: '895845013571',
    projectId: 'on-stage-app-firebase-server',
    storageBucket: 'on-stage-app-firebase-server.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdmHi1RlzP6TUcE16YsQj-daeombVFCf0',
    appId: '1:895845013571:ios:34083e5ce55e753b2f9cf6',
    messagingSenderId: '895845013571',
    projectId: 'on-stage-app-firebase-server',
    storageBucket: 'on-stage-app-firebase-server.firebasestorage.app',
    androidClientId: '895845013571-8llikk9sqpamqcf790t0fvg25g3thk15.apps.googleusercontent.com',
    iosClientId: '895845013571-j78fsqbihesjarrijqaelec90c7in36h.apps.googleusercontent.com',
    iosBundleId: 'com.onstage.app',
  );

}