name: on_stage_app

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ToniVinter/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      test_recursion: false
      test_optimization: false
      min_coverage: 0



  spell-check:
    uses: ToniVinter/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
      modified_files_only: false